apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-services
  labels:
    app: nginx
    name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
      name: nginx
  template:
    metadata:
      labels:
        app: nginx
        name: nginx
    spec:
      containers:
      - image: 840891909344.dkr.ecr.us-east-1.amazonaws.com/workshop:docker-http-server
        name: nginx
        ports:
        - name: http
          containerPort: 80